config/routes.rb
Elmorfstore::Application.routes.draw do

  get "page/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  match 'store' => 'store#index', :as => 'store', :via => :get
  match 'shoppingcart' => 'store#show_cart', :as => 'shoppingcart', :via => :get
  match 'add_to_cart/:id' => 'store#add_to_cart', :as => 'add_to_cart'
  match 'store' => 'store#empty_cart', :via => :delete
  match 'checkout' => 'store#checkout', :as => 'checkout'
  match 'saveorder' => 'store#save_order', :as => 'save_order', :via => :get
  match 'store/product/:id' => 'store#show', :as => 'show_product', :via => :get
  match 'confirm' => 'store#confirm_order', :as => 'confirm_order', :via => :post
  match 'confirm' => 'store#confirm_order', :as => 'confirm_order', :via => :put
  match 'pages/:id/:permalink' => 'page#show', :as => 'page', :via => :get

root :to => 'store#index'

resources :orders, :products

end

app/models/order.rb
class Order < ActiveRecord::Base
  ORDER_STATUS = ["Shipped", "Pending", "Order Requested"] 
  attr_accessible :address, :email, :first_name, :last_name, :status, :gst, :hst, :pst
  has_many :lineitems
  validates :address, :presence => true
  validates :email, :presence => true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates_inclusion_of :status, :in => ORDER_STATUS

  def add_products_from_cart(cart)
  	cart.items.each do |item|
  		lineitem = Lineitem.add_from_cart_item(item)

  		lineitems << lineitem
  	end
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to admin_orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for [:admin, @order] do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Order::ORDER_STATUS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.first_name %></td>
    <td><%= order.last_name %></td>
    <td><%= order.email %></td>
    <td><%= order.address %></td>
    <td><%= link_to 'Show', admin_order_path(order) %></td>
    <td><%= link_to 'Edit', edit_admin_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_admin_order_path %>

app/views/admin/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @order.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @order.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @order.email %>
</p>

<p>
  <b>Address:</b>
  <%= @order.address %>
</p>


<%= link_to 'Edit', edit_admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %>