config/routes.rb
Elmorfstore::Application.routes.draw do

  get "page/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  match 'store' => 'store#index', :as => 'store', :via => :get
  match 'shoppingcart' => 'store#show_cart', :as => 'shoppingcart', :via => :get
  match 'add_to_cart/:id' => 'store#add_to_cart', :as => 'add_to_cart'
  match 'store' => 'store#empty_cart', :via => :delete
  match 'checkout' => 'store#checkout', :as => 'checkout'
  match 'saveorder' => 'store#save_order', :as => 'save_order', :via => :get
  match 'store/product/:id' => 'store#show', :as => 'show_product', :via => :get
  match 'confirm' => 'store#confirm_order', :as => 'confirm_order', :via => :post
  match 'confirm' => 'store#confirm_order', :as => 'confirm_order', :via => :put
  match 'pages/:id/:permalink' => 'page#show', :as => 'page', :via => :get

root :to => 'store#index'

resources :orders, :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :stock_no, :available, :category_id, :image

  scope :unavailable, where(:available => nil || :available.empty?)
  has_many :lineitems
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates :description, :presence => true
  validates :name, :presence => true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }, :presence => true
  validates :stock_no, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
  #validates :image, :format => { :with => %r{\.(gif|jpe?g|png)$}i }
  belongs_to :category

  def self.available_items
  	find(:all,
  		 :conditions => { :available => true} )
  end 

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock_no %><br />
    <%= f.number_field :stock_no %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Stock no</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= product.stock_no %></td>
    <td><%= link_to 'Show', admin_product_path(product) %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
    <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Stock no:</b>
  <%= @product.stock_no %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>