config/routes.rb
Elmorfstore::Application.routes.draw do

  get "page/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  match 'store' => 'store#index', :as => 'store', :via => :get
  match 'shoppingcart' => 'store#show_cart', :as => 'shoppingcart', :via => :get
  match 'add_to_cart/:id' => 'store#add_to_cart', :as => 'add_to_cart'
  match 'store' => 'store#empty_cart', :via => :delete
  match 'checkout' => 'store#checkout', :as => 'checkout'
  match 'saveorder' => 'store#save_order', :as => 'save_order', :via => :get
  match 'store/product/:id' => 'store#show', :as => 'show_product', :via => :get
  match 'confirm' => 'store#confirm_order', :as => 'confirm_order', :via => :post
  match 'confirm' => 'store#confirm_order', :as => 'confirm_order', :via => :put
  match 'pages/:id/:permalink' => 'page#show', :as => 'page', :via => :get

root :to => 'store#index'

resources :orders, :products

end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  before_filter :instantiate_cart, :only => [:add_to_cart, :show_cart, :confirm_order, :save_order, :empty_cart, :checkout]

  def index
  	@products = Product.available_items
  end

  def instantiate_cart
    @cart = get_cart
  end

  def add_to_cart
  	product = Product.find(params[:id])
  	@cart.add_cart_item(product)
  	redirect_to store_path
  end

  def show
    @product = Product.find(params[:id])
  end

  def show_cart
  	@items = @cart.items
    if @items.empty?
      redirect_to store_path
      flash[:notice] = "Your cart is currently empty"
    else 
      render 'shoppingcart'
    end

  end

  def confirm_order
    @provinces = Province.all

    if session['user_id'].present?
      @user = User.find(session[:user_id])
      @order = Order.new(:first_name => @user.first_name, :last_name => @user.last_name, :status => "Pending", :email => @user.email, :address => @user.address)
      add_taxes(@order, @user.province)
    else
      @user = User.new(params[:user])
      if @user.valid?
        @order = Order.new(:first_name => @user.first_name, :last_name => @user.last_name, :status => "Pending", :email => @user.email, :address => @user.address)
        add_taxes(@order, @user.province)
      else 
        render 'checkout'
      end
    end

    session[:order] = @order
    @items = @cart.items

    if @order
      taxes = { pst: @order.pst, gst: @order.gst, hst: @order.hst }
      @grand_total = @cart.grand_total taxes
    end
    

  end

  def save_order

    @order = session[:order]
    @order.add_products_from_cart(@cart)
    if @order.save
      session[:cart] = nil
      session[:order] = nil
      redirect_to root_path
      flash[:notice] = "Your order has been placed"
    else
      render :controller => :store, :action => :checkout
    end
  end

  def empty_cart
    @cart.empty_cart_contents!
    flash[:notice] = ' Your cart is now empty'
    redirect_to store_path
  end

  def checkout
    @user = User.new 
    if session['user_id'].present?
      @user = User.find(session[:user_id]) 
    end
    
    @provinces = Province.all

    @items = @cart.items
    if @items.empty?
      redirect_to root_path("There's nothing in your cart")
    end
  end

private

  def get_cart
  	session[:cart] ||= Cart.new
  end

  def add_taxes(order, province)
    order.hst = province.hst
    order.gst = province.gst
    order.pst = province.pst
  end


end

app/helpers/store_helper.rb
module StoreHelper
	def span_label label
		content_tag(:span, :class => 'label') do 
			label
		end
	end 

	def span_value value
		content_tag(:span, :class => 'value') do
			"#{value}"
		end 
	end 


end

app/views/store/_items_in_cart.html.erb
<section class="items_in_cart">
	<section class="item_in_cart">
		<section class="cart_item_image">
			<%= image_tag item.product.image, :class => "item_image" if item.product.image.present? %>
		</section>
		<section class="cart_item_information">
			<section class="item_info">
				<%= span_label 'Product Name:' %>
				<%= span_value item.product.name %>
			</section>
			<section class="item_info">
				<%= span_label 'Quantity:' %>
				<%= span_value item.quantity %>
			</section>
			<section class="item_info">
				<%= span_label 'Price: ' %>
				<%= span_value number_to_currency(item.price) %>
			</section>
		
		</section>
		
	</section>	
</section>

app/views/store/_product.html.erb
<section class="product">
	<header><%= link_to product.name, show_product_path(product) %></header>
		<section class="product_image">
			<%= image_tag product.image if product.image.present? %>
		</section>
		<section class="product_info">
			<span class="label">Price: </span>
			<span class="value"><%= number_to_currency(product.price) %></span>

		</section>
	<footer class="product_buy">
		<%= link_to 'Buy Now', add_to_cart_path(product) %>
		
	</footer>
</section>

app/views/store/_user_checkout_info.erb
<section class="user_checkout_information">

	<section class="user_info">
		<%= span_label 'Name:' %>
		<%= span_value user.first_name+ " " +user.last_name %>
	</section>

	<section class="user_info">
		<%= span_label 'Address: '%>
		<%= span_value user.address + " " + user.province.name  %>
	</section>

	<section class="user_info">
		<%= span_label 'Email Address: '%>
		<%= span_value user.email  %>
	</section>
	
</section>

app/views/store/checkout.html.erb
<section id="shoppingcart">

	<%= render :partial => 'items_in_cart', :collection => @items, :as => 'item' %>

	<%= form_for @user, :url => confirm_order_path do |f| %>
		<% if !session['user_id'].present? %>

			<% if @user.errors.any? %>
				<section class="error">
					<h2>Form is invalid</h2>
					<ul>
						<% for message in @user.errors.full_messages %>
						<li><%= message %></li>
						<% end %>
					</ul>
				</section>
			<% end %>

			<section class="field">
				<%= f.label :first_name %>
				<%= f.text_field :first_name %>
			</section>
			<section class="field">
				<%= f.label :last_name %>
				<%= f.text_field :last_name %>
			</section>
			<section class="field">
				<%= f.label :email %>
				<%= f.email_field :email %>
			</section>
			<section class="field">
				<%= f.label :address %>
				<%= f.text_field :address %>
			</section>
			<section class="field">
				<%= f.label :province_id %>
				<%= f.collection_select :province_id, @provinces, :id, :name %>
			</section>
			<section class="field">
				<%= f.hidden_field :password, :value => "temp" %>
			</section>
			
			<section class="field">
				<%= f.hidden_field :password_confirmation, :value => "temp" %>
			</section>

		<% else %>
		<%= render :partial => 'user_checkout_info', :object => @user, :as => 'user' %>
		<% end%>
		<section class="field">
			<%= submit_tag 'Place Order', :id => "submit" %>
		</section>
	
	<% end %>

</section>

app/views/store/confirm_order.html.erb
<section id="shoppingcart">

	<%= render :partial => 'items_in_cart', :collection => @items, :as => 'item' %>
	
	<section id="confirm_summary">
		
		<section class="summary_info">
			<%= span_label 'Sub-total: '%>
			<%= span_value number_to_currency(@cart.total_price) %>
		</section>


		<% unless @order.gst.zero? %>
		<section class="summary_info">
			<%= span_label 'GST:' %>
			<%= span_value "#{tax_percent @order.gst}  #{number_to_currency(@cart.total_with_tax @order.gst)}" %>
		</section>	
		<% end %>

		<% unless @order.pst.zero? %>
		<section class="summary_info">
			<%= span_label 'PST:' %>
			<%= span_value "#{tax_percent @order.pst}  #{number_to_currency(@cart.total_with_tax @order.pst)}" %>
		</section>
		<% end %>
		<% unless @order.hst.zero? %>
		<section class="summary_info">
			<%= span_label 'HST' %>
			<%= span_value "#{tax_percent @order.hst}  #{number_to_currency(@cart.total_with_tax @order.hst)}" %>
		</section>
		

		<% end %>

		<section class="summary_info">
			<%= span_label 'Grand-total: '%>
			<%= span_value number_to_currency(@grand_total) %>
		</section>

	</section>
	<section class="confirm_link">
		<%= link_to 'Confirm Order', save_order_path %>
	</section>
	


</section>

app/views/store/index.html.erb
<section id="products">
<%= render :partial => 'product', :collection => @products, :as => 'product' %>
</section>

app/views/store/shoppingcart.html.erb
<% title "Shopping Cart" %>

<header class="shoppingcart">
	<h1>Display Cart Check</h1>
</header>
<section id="shoppingcart">
	

	
	
	<%= render :partial => 'items_in_cart', :collection => @items, :as => 'item' %>
	<section class="shopping_cart_summary">
		<section class="summary_info">
			<%= span_label 'Cart Contains: '%>
			<%= span_value pluralize @items.size, 'item' %>
		</section>

		<section class="summary_info">
			<%= span_label 'Total: ' %>
			<%= span_value number_to_currency @cart.total_price%></section>
		</section>


		<section class="checkoutlinks">
			<nav>
				<ul>
					<li><%= link_to 'Continue shopping', store_path %></li>
					<li><%= link_to 'Empty cart', store_path, :method => :delete %></li>
					<li><%= link_to 'Checkout', checkout_path %></li>
				</ul>
			</nav>
		</section>

	</section>

app/views/store/show.html.erb
<section class="product_show">
	
	<section class="product_image">
		<%= image_tag @product.image %>
	</section>
	<section class="product_info">
		<header>
		<%= @product.name %>
		</header>
		<section class="info">
			<span class="label">Price: </span>
			<span class="value"><%= @product.price %></span>
		</section>
		
		<section class="info">
			<span class="label">Description: </span>
			<span class="value"><%= @product.description %></span>
		</section>
		<section class="info">
			<span class="label">Category: </span>
			<span class="value"><%= @product.category.name %></span>
		</section>
		<footer><%= link_to 'Buy Now', add_to_cart_path(@product) %></footer>
	</section>

	
</section>