config/routes.rb
Elmorfstore::Application.routes.draw do

  get "page/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  match 'store' => 'store#index', :as => 'store', :via => :get
  match 'shoppingcart' => 'store#show_cart', :as => 'shoppingcart', :via => :get
  match 'add_to_cart/:id' => 'store#add_to_cart', :as => 'add_to_cart'
  match 'store' => 'store#empty_cart', :via => :delete
  match 'checkout' => 'store#checkout', :as => 'checkout'
  match 'saveorder' => 'store#save_order', :as => 'save_order', :via => :get
  match 'store/product/:id' => 'store#show', :as => 'show_product', :via => :get
  match 'confirm' => 'store#confirm_order', :as => 'confirm_order', :via => :post
  match 'confirm' => 'store#confirm_order', :as => 'confirm_order', :via => :put
  match 'pages/:id/:permalink' => 'page#show', :as => 'page', :via => :get

root :to => 'store#index'

resources :orders, :products

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title>
  	Elmorfstore
  	<% if(yield(:title) != "")%>
  		<%= " - " + yield(:title) %>
  	<% end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<section id="container">
		<header class="main">
			<section id="logo">
				<img src="/assets/logo.png" alt="Logo" />
			</section>
			<nav class="main">
				<ul>
					<li><%= link_to 'Home', root_path %></li>

					<% unless @pages.empty? %>
						<% @pages.each do |page| %>
							<li><%= link_to page.title, "/pages/#{page.id}/#{page.permalink}" %></li>
						<% end %>
					<% end %>

					<li><%= link_to 'Shopping Cart', shoppingcart_path %></li>
					<li><%= link_to 'Admin', admin_root_path %></li>
				</ul>
			</nav>
			<nav class="sub">
				<% if current_user %>
					Logged in as <%= current_user.email %>
					<%= link_to "Log out", log_out_path %>
				<% else %>
					<%= link_to "Sign up", sign_up_path %>
					<%= link_to "Sign in", log_in_path %>
				<% end %>
			</nav>
		</header>
		
		<section id="content">
			<% if flash[:notice] %>
		      <section class="notice"><%= flash[:notice] %></section>
		    <% end %>
		    <% if flash[:error] %>
		      <section class="error"><%= flash[:error] %></section>
		    <% end %>
			<%= yield %>
		</section>
	</section>
	<section id="clear_footer"></section>
	
	<footer class="main">
		<section id="footer_amplifier"></section>
		<section id="footer_container">
			<ul>
				<% unless @footer_links.empty? %>
						<% @footer_links.each do |link| %>
							<li><%= link_to link.name, "#{link.url}" %></li>
						<% end %>
					<% end %>
			</ul>
		</section>
		
	</footer>


</body>

</html>